detectKills: true
watchCommands: true
allowSigns: true
resetPointsAfterEachPromotion: true
updateUsernames: true 
startInPromotionTree: true 
lowestRankThatCanManuallyApproveAims: admin
defaultPoints: 0
commands: []
defaultTarget: target1 
aims: 
  aim1:
    type: none 
    achieve: none 
targets: 
  target1:
    aims:
    - aim1 
    commands: none 
    defaultNextTarget: none 
    leadsTo: 
    - none 
