name: PromoteOneself
main: me.PromoteOneselfPackage.PromoteOneself.Classes.PromoteOneselfMainClass 
version: Development_11.0.2.2
description: A plugin which lets people achieve aims to work up through a server's ranking system 
author: aappleton3 
database: false
softdepend: [Vault, PlayerPoints] 
commands:
  promoteoneself:
    description: Command to show the command for help 
    usage: /promoteoneself 
  prom: 
    description: Commands that update a player's status 
    usage: /prom <arguments> 
  posset:
    description: Mostly operator commands 
    uasage: /posset <arguments> 
permissions:
  pos.*:
    description: Use all commands concerning the PromoteOneself plugin 
    default: op
    children:
      pos.save: true
      pos.reload.*: true
      pos.update.*: true
      pos.password.*: true
      pos.check.*: true
      pos.list.*: true
      pos.exempt.*: true
      pos.player.*: true
      pos.set.*: true
      pos.promote.*: true
      pos.sign.*: true
  pos.save:
    description: The player can save the configuration 
    default: op
  pos.reload.*:
    description: The player can reload the configuration 
    default: op
    children:
      pos.reload.check: true
      pos.reload.nocheck: true
  pos.reload.check:
    description: The player can reload the configuration and ensure that all player aims are correct 
    default: op
  pos.reload.nocheck:
    description: The player can reload the configuration without ensuring that all player aims are correct 
    default: op
  pos.update.*:
    description: Update players' aims 
    default: op
    children: 
      pos.update.others: true
      pos.update.add.others: true
      pos.update.target.others: true
      pos.update.aim.others: true
  pos.update.others:
    description: Update another player's aims 
    default: op
    children:
      pos.update: true
  pos.update:
    description: Update ones own aims 
    default: op
  pos.update.add.others:
    description: Add other people to the promotion tree
    default: op
    children:
      pos.update.add: true
  pos.update.add:
    description: Add oneself to the promotion tree 
    default: op
  pos.update.target.others:
    description: Update a player's aims and set which target it should advance to next 
    default: op
    children: 
      pos.update.target: true
  pos.update.target:
    description: Update ones own aims and set which target oneself should advance to next 
    default: op
  pos.update.aim.others: 
    description: Update an individual aim of a player without causing the player to advance 
    default: op
    children: 
      pos.update.aim: true
  pos.update.aim:
    description: Update ones own aims without advancing to a new target 
    default: op
  pos.password.*:
    description: Get someone set and get player's guesses at passwords for aims 
    default: op 
    children:
      pos.password.get.others: true
      pos.password.set.others: true
  pos.password.get.others:
    description: Get the password that a player has set as a guess to an aim 
    default: op
    children:
      pos.password.get: true
  pos.password.get:
    description: Let a player get the password that it has set as the answer to an aim 
    default: op
  pos.password.set.others:
    description: Set the password that a player will use as a guess to an aim 
    default: op
    children:
      pos.password.set: true 
  pos.password.set:
    description: Let a player set the password that it will use as the answer to an aim 
    default: op
  pos.check.*: 
    description: Can check all object types 
    default: op
    children: 
      pos.check.others: true
      pos.check.targets: true
      pos.check.aims.full: true 
      pos.check.signs: true
      pos.check.configs: true
  pos.check.others:
    description: Check a players' aims 
    default: op
    children:
      pos.check: true
  pos.check:
    description: Check ones own aims 
    default: op
  pos.check.targets:
    description: Check a target 
    default: op
  pos.check.aims.full: 
    description: Check an aim including data such as the required password of a password type aim 
    default: op
    children:
      pos.check.aims: true
  pos.check.aims:
    description: Check an aim 
    default: op
  pos.check.signs:
    description: Check a sign's maximum usage 
    default: op
  pos.check.configs:
    description: Check a config file's saveable status 
    default: op
  pos.list.*:
    description: Can list the names of all object types
    default: op
    children:
      pos.list.targets: true
      pos.list.aims: true
      pos.list.players: true
      pos.list.exempt: true
      pos.list.signs: true
      pos.list.configs: true
  pos.list.targets:
    description: Can list the names of all targets 
    default: op
  pos.list.aims:
    description: Can list the names of all aims
    default: op
  pos.list.players:
    description: Can list the names of all players
    default: op
  pos.list.exempt:
    description: Can list the names of all exempt players
    default: op
  pos.list.signs:
    description: Can list the ids of all signs
    default: op
  pos.list.configs:
    description: Can list the names of all the config files 
    default: op
  pos.exempt.*:
    description: Set a player's exemption status 
    default: op 
    children:
      pos.exempt.true: true
      pos.exempt.temp: true
      pos.exempt.add: true
      pos.exempt.join: true
  pos.exempt.true:
    description: Make a player exempt 
    default: op
  pos.exempt.temp:
    description: Temporarily make a player exempt 
    default: op
  pos.exempt.add:
    description: Make a player loose exemption on its next join 
    default: op
  pos.exempt.join:
    description: Instantly make a player loose exemption 
    default: op
  pos.player.*:
    description: Have the ability to add, delete and reset all players 
    default: op
    children: 
      pos.update.add.others: true
      pos.player.remove.others: true
      pos.player.reset.others: true
  pos.player.remove.others:
    description: Remove the information about a player 
    default: op
    children: 
      pos.player.remove: true
  pos.player.remove:
    description: Remove the information about oneself 
    default: op
  pos.player.reset.others:
    description: Reset the information about other players 
    default: op
    children:
      pos.player.reset: true
  pos.player.reset:
    description: Reset the information about oneself 
    default: op
  pos.set.*:
    description: Have the ability to set all settable information 
    default: op
    children:
      pos.set.player.*: true
      pos.set.target.*: true
      pos.set.aim.*: true
      pos.set.setting.*: true
      pos.set.sign.*: true 
  pos.set.player.*:
    description: Set all settable information about any player 
    default: op
    children:
      pos.set.player.aim: true
      pos.set.player.finished: true
      pos.set.player.target: true
      pos.set.player.sign: true
      pos.set.player.password: true
      pos.set.player.points: true
      pos.set.player.kills: true
      pos.set.player.player: true
  pos.set.player.aim:
    description: Set the completion status of an aim of a player 
    default: op
    children:
      pos.set.player.aim.none: true
  pos.set.player.aim.none:
    description: Set the completion status of a 'none' type aim of a player 
    default: op 
  pos.set.player.finished: 
    description: Set the completion status of a player's promotion tree 
    default: op
  pos.set.player.target: 
    description: Set a player's target 
    default: op
  pos.set.player.sign:
    description: Set the number of times the player has used a sign 
    default: op
  pos.set.player.password:
    description: Set the password that a player will use as a guess to an aim 
    default: op
  pos.set.player.points:
    description: Set a player's points 
    default: op
  pos.set.player.kills:
    description: Set a player's kills 
    default: op
  pos.set.player.player:
    description: Update a player's atored username 
    default: op
  pos.set.target.*:
    description: Set all settable information about any target 
    default: op
    children:
      pos.set.target.aims: true
      pos.set.target.leadsto: true
      pos.set.target.defaultnexttarget: true
  pos.set.target.aims:
    description: Set the aims of a target 
    default: op
  pos.set.target.leadsto:
    description: Set which targets a target leads to 
    default: op
  pos.set.target.defaultnexttarget:
    description: Set which target should be the default next target of a target 
    default: op
  pos.set.aim.*:
    description: Set all settable information about aims 
    default: op
    children: 
      pos.set.aim.type: true
      pos.set.aim.achieve: true
  pos.set.aim.type:
    description: Set an aim's type 
    default: op
  pos.set.aim.achieve:
    description: Set an aim's goal 
    default: op
  pos.set.setting.*:
    description: Set the main settings about the PromoteOneself plugin 
    default: op
    children: 
      pos.set.setting.defaulttarget: true
      pos.set.setting.lowestrankthatcanmanuallyapproveaims: true
      pos.set.setting.startinpromotiontree: true
      pos.set.setting.updateusernames: true
      pos.set.setting.detectkills: true
      pos.set.setting.resetpointsaftereachpromotion: true
      pos.set.setting.allowsigns: true
      pos.set.setting.watchcommands: true
      pos.set.setting.defaultpoints: true
      pos.set.setting.alwayssavefiles: true
      pos.set.setting.remindonjoin: true
  pos.set.setting.defaulttarget:
    description: Set the default starting target 
    default: op
  pos.set.setting.lowestrankthatcanmanuallyapproveaims:
    description: Tell the plugin which rank has the pos.set.player.aim permission 
    default: op
  pos.set.setting.startinpromotiontree:
    description: Set whether or not all players should automatically start inside the promotion tree 
    default: op
  pos.set.setting.updateusernames:
    description: Set whether or not players' usernames should be automatically updated 
    default: op
  pos.set.setting.detectkills:
    description: Set whether this plugin should listen for player kills or not 
    default: op
  pos.set.setting.resetpointsaftereachpromotion:  
    description: Set whether this plugin should resets players' points after each promotion or not 
    default: op
  pos.set.setting.allowsigns:
    description: Set whether this plugin listens to signs or not 
    default: op
  pos.set.setting.watchcommands:
    description: Set whether 'command' type aims should work or not 
    default: op
  pos.set.setting.defaultpoints:
    description: Set the default number of points players should have 
    default: op
  pos.set.setting.alwayssavefiles:
    description: Set if files that the plugin couldn't load properly should be saved regardless (this may wipe the files) 
    default: op
  pos.set.setting.remindonjoin:
    description: Set if the plugin should send a reminder message to players each time they join 
    default: op
  pos.set.sign.*:
    description: Set all setable items about signs 
    default: op
    children:
      pos.set.sign.usage: true
  pos.set.sign.usage:
    description: Set the usage limit for a sign id group 
    default: op 
  pos.promote.*:
    description: Let the player be promoted to any group (only required for permission type aims) 
    default: op
  pos.sign.*:
    description: Let the player create, delete and use all signs 
    default: op
    children:
      pos.sign.id.*: true
      pos.sign.noid: true
      pos.sign.update.*: true
      pos.sign.points.*: true
      pos.sign.target.*: true
      pos.sign.sign.*: true
      pos.sign.aim.*: true
      pos.sign.limitexempt.*: true
  pos.sign.id.*:
    description: Let the player use any sign with an id 
    default: op
  pos.sign.noid:
    description: Let the player use signs with no ids 
    default: op
  pos.sign.update.*:
    description: Let the player create, delete and use update type signs 
    default: op 
    children:
      pos.sign.update.use.add: true
      pos.sign.update.create: true
      pos.sign.update.delete: true
  pos.sign.update.use.add:
    description: Let the player use update type signs to add itself to the promotion tree 
    default: op
    children:
      pos.sign.update.use: true
  pos.sign.update.use:
    description: Let the player use update type signs 
    default: op
  pos.sign.update.create:
    description: Let the player create update type signs 
    default: op
  pos.sign.update.delete:
    description: Let the player delete update type signs 
    default: op
  pos.sign.points.*:
    description: Let the player create, delete and use points type signs 
    default: op
    children:
      pos.sign.points.use: true
      pos.sign.points.create: true
      pos.sign.points.delete: true
  pos.sign.points.use:
    description: Let the player use points type signs 
    default: op
  pos.sign.points.create:
    description: Let the player create points type signs 
    default: op
  pos.sign.points.delete:
    description: Let the player delete points type signs 
    default: op
  pos.sign.target.*:
    description: Let the player create, delete and use target type signs 
    default: op 
    children:
      pos.sign.target.use: true
      pos.sign.target.create: true
      pos.sign.target.delete: true
  pos.sign.target.use:
    description: Let the player use target type signs 
    default: op
  pos.sign.target.create:
    description: Let the player create target type signs 
    default: op
  pos.sign.target.delete:
    description: Let the player delete target type signs 
    default: op
  pos.sign.sign.*:
    description: Let the player create, delete and use sign type signs 
    default: op
    children:
      pos.sign.sign.use: true
      pos.sign.sign.create: true
      pos.sign.sign.delete: true
  pos.sign.sign.use:
    description: Let the player use sign type signs 
    default: op
  pos.sign.sign.create: 
    description: Let the player create sign type signs 
    default: op
  pos.sign.sign.delete:
    description: Let the player delete sign type signs 
    default: op 
  pos.sign.aim.*:
    description: Let the player create, delete and use aim type signs 
    default: op
    children:
      pos.sign.aim.use: true
      pos.sign.aim.create: true
      pos.sign.aim.delete: true
  pos.sign.aim.use:
    description: Let the player use aim type signs 
    default: op
  pos.sign.aim.create:
    description: Let the player create aim type signs 
    default: op
  pos.sign.aim.delete:
    description: Let the player delete aim type signs 
    default: op
  pos.sign.limitexempt.*:
    description: Be exempt from all sign usage limits 
    default: op 
